"use strict";

var ADDRESS_SIZE = 34;
var ADDRESS_PREFIX = "41";
var ADDRESS_PREFIX_BYTE = 0x41;
var ADDRESS_PREFIX_REGEX = /^(41)/;
module.exports = {
  ADDRESS_SIZE: ADDRESS_SIZE,
  ADDRESS_PREFIX: ADDRESS_PREFIX,
  ADDRESS_PREFIX_BYTE: ADDRESS_PREFIX_BYTE,
  ADDRESS_PREFIX_REGEX: ADDRESS_PREFIX_REGEX
};